// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALbYdehFuMMve-j2LIZ_G4HrTPKMwC4Bo',
    appId: '1:872506616131:android:4a7f642d3abf63067327f6',
    messagingSenderId: '872506616131',
    projectId: 'mxpertz-cd67c',
    databaseURL: 'https://mxpertz-cd67c-default-rtdb.firebaseio.com',
    storageBucket: 'mxpertz-cd67c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpEzEL5HGhTuTTnKT0u21fSZRUQHnqq0U',
    appId: '1:872506616131:ios:294732417a61bbf17327f6',
    messagingSenderId: '872506616131',
    projectId: 'mxpertz-cd67c',
    databaseURL: 'https://mxpertz-cd67c-default-rtdb.firebaseio.com',
    storageBucket: 'mxpertz-cd67c.firebasestorage.app',
    androidClientId: '872506616131-h2lve2nbahuqb517g4a58ri4h7mpnt2v.apps.googleusercontent.com',
    iosClientId: '872506616131-pfj75o0dkugu4ecjqq5ods1t5grtc4in.apps.googleusercontent.com',
    iosBundleId: 'mxpertz.com.mxpertz',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "YOUR_WEB_API_KEY",
    authDomain: "YOUR_PROJECT.firebaseapp.com",
    projectId: "YOUR_PROJECT_ID",
    storageBucket: "YOUR_PROJECT.appspot.com",
    messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
    appId: "YOUR_WEB_APP_ID",
  );
}